// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using study_aspnetcore1.Models;

namespace study_aspnetcore1.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("study_aspnetcore1.Models.AModel", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("A1");

                    b.Property<string>("A2");

                    b.HasKey("ID");

                    b.ToTable("AModels");
                });

            modelBuilder.Entity("study_aspnetcore1.Models.BModel", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("B1");

                    b.Property<string>("B2");

                    b.HasKey("ID");

                    b.ToTable("BModels");
                });
#pragma warning restore 612, 618
        }
    }
}
